name: Build for Linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build libgtk-3-dev
          java -version

      - name: Install Flutter
        run: |
          git submodule update --init --recursive

      - name: Prepare Flutter Dependencies
        run: |
          .flutter/bin/flutter config --no-analytics
          .flutter/bin/flutter pub get

      - name: Build
        run: |
          .flutter/bin/flutter build linux --release

      - name: Package
        working-directory: build/linux/x64/release/bundle
        run: |
          7z a -r "../../../../../build/app/watermeter-linux-release-amd64.zip" *

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Watermeter_Linux
          path: |
            build/app/watermeter-linux-release-*.zip