name: Build for Android

on:
  workflow_call:
  workflow_dispatch:

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
  
      - name: Install Flutter and Flutter Dependencies
        run: |
          git submodule update --init --recursive
          .flutter/bin/flutter config --no-analytics
          .flutter/bin/flutter pub get

      - name: Build
        run: |
          .flutter/bin/flutter build apk --target-platform=android-arm64 --split-per-abi --no-shrink --no-sign

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          if-no-files-found: error
          name: TraintimePDA_Android
          path: |
            build/app/outputs/flutter-apk/app-*-release.apk
            build/app/outputs/bundle/release/app-release.aab
