name: Release for Android

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build for Android
    uses: ./.github/workflows/build_for_android.yml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.4

      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          prerelease: false
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            TraintimePDA_Android/flutter-apk/app-*-release.apk
            TraintimePDA_Android/bundle/release/app-release.aab
